if: commit_message !~ /auto\/ci:\sset\sversion/
language: node_js
node_js:
  - "12.16.3"
git:
  depth: false
cache:
  directories:
    - node_modules
script:
  - git remote set-url origin https://$USER:$GITHUB_API_KEY@github.com/eigen-space/base-http-service.git
  # We use additional dashes here `--` because
  # It is needed to separate the params passed to npm command itself and params passed to your script
  - yarn lint && yarn test:ci && yarn build && npm run deploy:publish -- --branch=$TRAVIS_BRANCH;
before_install:
  - echo "registry=https://$REGISTRY/" >> .npmrc
  - echo "//$REGISTRY/:_authToken=$ACCESS_TOKEN" >> .npmrc